# WORK IN PROGRESS
version: '3.8'
services:
  ollama-telegram:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ollama-telegram
    restart: no
    hostname: azura-dockerized
    env_file:
      - ./.env
  
  ollama-server:
    image: ollama/ollama:latest
    container_name: ollama-server
    volumes:
      - ./ollama:/root/.ollama
    
    # Uncomment to enable NVIDIA GPU
    # Otherwise runs on CPU only:

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    restart: always
    ports:
      - '11434:11434'
